### 버스 정류장 검색 API
### URL : localhost:8080/bus/stopinfo/stopinfo/{busStopName} | 인코딩 된 문자열 : 우미린
GET localhost:8080/bus/stopinfo/adsf

### 실시간 버스 도착정보 검색 API
### URL : localhost:8080/bus/stopinfo/arrival/{busStopId} | 정류장 ID : 196020421 (우미린1차)
GET localhost:8080/bus/stopinfo/arrival/196020421

### 입력받은 위도/경도 정보로 제일 가까운 정류장 검색 API
### URL : localhost:8080/bus/location/user/{latitude}/{longitude}
GET localhost:8080/bus/location/user/35.576069/129.241947

### 버스 정류장 정보 저장 API
POST localhost:8080/bus/stopinfo

### 버스 노선 정보 저장 API
POST localhost:8080/bus/routeinfo

### 버스 정류장별 노선 정보 저장 API
# @timeout 30 m
// @connection-timeout 30 m
POST localhost:8080/bus/stoprouteinfo

### 버스 노선별 시간표 저장 API
# @timeout 30 m
// @connection-timeout 30 m
POST localhost:8080/bus/timetable
